language : c #not really, but don't need anything else setup

before_install :
  - quickinstall/bin/travis-ssh.sh && cd quickinstall


install :
  - make install

script :
  - make test

after_script :
  - make stop clean
